# - name: Fix extensions
#   command: "/Users/travis/.rvm/bin/rvm all do gem pristine --all"

- name: Install all available simulator runtimes
  xcode_simulator:
    xcode: "{{ xcode_version }}"
  retries: 3
  delay: 3
  register: result
  until: result is succeeded
  environment:
    GEM_HOME: "/Users/travis/.rvm/gems/ruby-2.7.0"
    GEM_PATH: "/Users/travis/.rvm/gems/ruby-2.7.0:/Users/travis/.rvm/gems/ruby-2.7.0@global"
    PATH: "{{ ansible_env.PATH }}:/Users/travis/.rvm/gems/ruby-2.7.0/bin/"
    XCODE_INSTALL_USER: "{{ xcode_install_user }}"
    XCODE_INSTALL_PASSWORD: "{{ xcode_install_password }}"

- name: Gather installed simulators
  command: xcrun simctl list
  register: simctl_list

- name: Write available simulators to file
  copy:
    content: "{{ simctl_list.stdout }}"
    dest: /tmp/simulators
