- name: Change default shell to bash
  import_tasks: bash.yml

- name: Configure sudoers
  import_tasks: sudo.yml

- name: Set up system preferences
  import_tasks: sys_prefs.yml

- name: Copy dotfiles
  import_tasks: dotfiles.yml