- name: Install swiftlint
  command: /usr/local/bin/brew install swiftlint
  
# - name: Install xctool
#   command: /usr/local/bin/brew install xctool

- name: Gather installed versions of packages
  command: /usr/local/bin/brew ls --versions
  register: brew_versions

- name: Write installed packages to file
  copy:
    content: "{{ brew_versions.stdout }}"
    dest: /tmp/brew_packages
