---
- import_playbook: site.yml
  vars:
    xcode_version: '13.2.1'
    nvm_version: v0.39.0
    node_versions:
    - 17.2.0    
    - 16.13.1
    - 15.14.0   
    - 14.18.1    
    - 13.14.0
    - 12.22.7
    - 11.15.0
    - 10.24.1
    rubies: [2.6.6]
    default_ruby: 2.6.6
    rvm_version: stable
